SM:
    MenuScreen:
    GameMain:
    GameLevelMenuScreen:
<MenuScreen>:
    BoxLayout:
        orientation: 'vertical'
        Button:
            text: 'Start Game'
            on_press:
                root.manager.current = 'start_game'
                root.manager.transition.direction = 'right'
        Button:
            text: 'Quit'
            on_press: app.stop() 
<GameMain>:
    name: 'start_game'
    on_enter: self.initial()


